- CRM/Certificate/Token/Event.php
- tests/phpunit/CRM/Certificate/Service/CertificateEventGeneratorTest.php
This PR resolves the issue with event token not being resolved when summary field is empty.
> WHFSPRT-243: Resolve issue with event token not resolved when summary is empty

- CRM/Certificate/Token/AbstractCertificateToken.php
In CiviCRM 5.51.3 the `Civi\Token\TokenProcessor` class no longer caches token categories in `context`, so in this PR we access it directly from the `\CRM_Utils_Token::getTokenCategories()` function.
> MAE-885: Access getTokenCategories directly

- .github/workflows/unit-test.yml
- CRM/Certificate/Test/Fabricator/CaseType.php
- CRM/Certificate/Token/AbstractCertificateToken.php
- tests/phpunit/BaseHeadlessTest.php
- tests/phpunit/CRM/Certificate/Token/CaseTest.php
In this PR we updated the PHP version to 8.0 and the CiviCRM version to 5.51.3 in the test workflow, one of the significant errors that were reported is
`undefined array key "hookTokenCategories"` because in CiviCRM 5.51.3 the `Civi\Token\TokenProcessor` class no longer caches token categories in `context`, to resolve this we access it directly from the `\CRM_Utils_Token::getTokenCategories()` function.
> MAE-885: Use PHP8 container in test workflow 

- CRM/Certificate/BAO/CompuCertificate.php
- CRM/Certificate/Form/CertificateConfigure.php
- CRM/Certificate/Test/Helper/Certificate.php
- tests/phpunit/BaseHeadlessTest.php
- tests/phpunit/CRM/Certificate/Entity/CaseTest.php
- tests/phpunit/CRM/Certificate/Entity/EventsTest.php
- tests/phpunit/CRM/Certificate/Entity/MembershipTest.php
- tests/phpunit/api/v3/CompuCertificate/GetcontactcertificatesTest.php
This PR allows the start_date and the end_date fields for the certificate configuration to be empty. such that, If a start date is set, the certificate will begin on that date and will assume to be available forever. However, if an end date is set, it will only be available until the end date.
start_date and end_date fields are mandatory.
start_date and end_date fields are optional.
The major change is replacing this condition:
```(start_date IS NULL OR end_date IS NULL OR start_date = CURRENT_DATE OR end_date = CURRENT_DATE OR CURRENT_TIMESTAMP BETWEEN start_date AND end_date)```
with
```(start_date IS NULL OR date(start_date) <= date(NOW())) AND (end_date IS NULL OR date(end_date) >= date(NOW()) )```
> FOSFAB-38: Allow empty start_date and end_date

- CRM/Certificate/Enum/CertificateType.php
This PR adds support for single certificate configuration with multiple membership types
Single certificate configuration can only be used with a membership type.
Single certificate configuration can be used with multiple membership types.
> FOSFAB-43: Support single certificate configuration with multiple membership types

- CRM/Certificate/Api/Wrapper/CompuCertificate.php
- CRM/Certificate/BAO/CompuCertificate.php
- CRM/Certificate/Entity/AbstractEntity.php
- CRM/Certificate/Entity/Case.php
- CRM/Certificate/Entity/EntityFactory.php
- CRM/Certificate/Entity/Event.php
- CRM/Certificate/Entity/Membership.php
- CRM/Certificate/Test/Fabricator/Relationship.php
- CRM/Certificate/Test/Fabricator/RelationshipType.php
- CRM/Certificate/Test/Helper/Case.php
- CRM/Certificate/Test/Helper/Event.php
- CRM/Certificate/Test/Helper/Membership.php
- api/v3/CompuCertificate/Getrelationshipcertificates.php
- tests/phpunit/api/v3/CompuCertificate/GetrelationshipcertificatesTest.php
This PR adds a new endpoint `CompuCertificate.Getrelationshipcertificates` that will be used by contacts to retrieve certificates they have access to based on a defined relationship.
API doesn't exist.
API Exists
The major change introduced by this PR is the method used in retrieving entity certificates based on configured  relationship types https://github.com/compucorp/uk.co.compucorp.certificate/blob/87217ac90748317f993018f6a6fb613e603992ce/CRM/Certificate/BAO/CompuCertificate.php#L74-L104
This code will translate to the SQL below:
```
SELECT compucertificate_certificate.id AS certificate_id,
compucertificate_certificate.start_date,
compucertificate_certificate.end_date,
name,
entity,
entity_type_id,
status_id,
template_id,
download_format,
contact_id_b AS related_contact,
contact_id_a …
```
> FOSFAB-44: Add Endpoint to retrieve contact certificates by relationship

- CRM/Certificate/BAO/CompuCertificate.php
- CRM/Certificate/Enum/DownloadFormat.php
- CRM/Certificate/Page/CertificateDownload.php
- CRM/Certificate/Service/CertificateAccessChecker.php
- CRM/Certificate/Service/CertificateDownloader.php
In this PR we grant a user download access to another user's certificate if they have the expected relationship with the user, we also allow a user to download a certificate HTML.
The user can download a certificate HTML by specifying `format=html` in the certificate download URL
> FOSFAB-47: Support HTML download and grant access via relationship

- CRM/Certificate/BAO/CompuCertificateImageFormat.php
- CRM/Certificate/Service/CertificateDownloader.php
- templates/CRM/Certificate/Page/CertificateDownload.tpl
In this PR we allow the use of the default image format.
The default image format was not used if no format was assigned to the message template.
The default image format is used if no format was assigned to the message template.
> FOSFAB-72: Use default image format

- CRM/Certificate/Service/CertificateDownloader.php
- templates/CRM/Certificate/Page/CertificateDownload.tpl
- templates/CRM/Certificate/Page/CertificateImageFormats.tpl
In this PR we handle situations where an image format is empty or not appropriately retrieved, so it doesn't break the download functionality, but instead, the system is able to default to the 'JPG' format.
> FOSFAB-37: Handle empty format properly

- CRM/Certificate/Form/CertificateImageFormats.php
This PR does the following:
- Fixes width and height validation when the image format form is edited.
> FOSFAB-82: Fix image format validation

- CRM/Certificate/Entity/Case.php
- CRM/Certificate/Entity/Event.php
- CRM/Certificate/Entity/Membership.php
This PR adds a try-catch block to methods that retrieve entity types and statuses, this is needed because it's possible that the entity type a certificate is attached to has been deleted, causing the API to throw an exception. The exception thrown is not an issue in CiviCRM itself as such exceptions are converted to alert messages, but they can break an SSP page. we simply wrap those API calls that are related to ssp_certificate functionality into the try-catch block.
> FOSFAB-102: Gracefully handle any error that might occur while retrieving certificate

- CRM/Certificate/Service/CertificateDownloader.php
- CRM/Certificate/Test/Fabricator/Contact.php
- CRM/Certificate/Token/Contact.php
- certificate.php
- tests/phpunit/CRM/Certificate/Token/ContactTest.php
In this PR we add support for a new token `{certificate_contact.employer_inline_address}`
No support for the token
The token `{certificate_contact.employer_inline_address}` when used in a certificate context will resolve to the address of the contact employer. Contact here refers to the contact the downloaded certificate belongs to.
> FOSFAB-102: Add token to get contact employer address 

- templates/CRM/Certificate/Form/CertificateConfigure.tpl
This PR hides the participant role description when creating a new certificate configuration
The description of the participant roles is displayed 
The description of the participant roles is not displayed
The reason for concealing the participant role descriptions is that they are created using a rich text editor, resulting in the presence of HTML tags when shown in the select field.
> CST-174: Hide participant role description

- CRM/Certificate/Token/AbstractCertificateToken.php
- CRM/Certificate/Token/Certificate.php
- tests/phpunit/CRM/Certificate/Token/CertificateTest.php
Handle multiple active memberships for a contact while evaluating the token values in such a way that the earliest start date and lattest end date is selected from all the currently active memberships.
N/A
N/A
> MMB-284: Handle Multiple Current Memberships

- CRM/Certificate/Token/AbstractCertificateToken.php
- CRM/Certificate/Token/Certificate.php
Add two new tokens for certificate validity dates 
1. “Valid From Date” {certificate.valid_from}
The latter of 1) the “Min Valid From Date” as configured for the certificate and 2) the users membership start date.
If the “Min Valid From Date” is null then we use the membership start date. 
2. “Valid To Date” {certificate.valid_to}
The earlier of 1) the “Max Valid Through Date” as configured for the certificate and 2) the users membership end date.
If the “Max Valid Through Date” is null then we use the membership end date.  
There were no certificate validity tokens.
> MMB-271: Add Certificate Validity Date Tokens

- CRM/Certificate/Entity/AbstractEntity.php
- CRM/Certificate/Entity/Membership.php
- CRM/Certificate/Service/Certificate.php
- CRM/Certificate/Service/CertificateAccessChecker.php
- CRM/Certificate/Service/CertificateMembership.php
- CRM/Certificate/Token/Certificate.php
- templates/CRM/Certificate/Form/CertificateConfigure.hlp
- templates/CRM/Certificate/Form/CertificateConfigure.tpl
This pr adjusts validity dates and tokens to be available just for membership type certificates.
The work was done for all types of certificates.
Its only applicable to membership type certificates.
> MMB-306: Restrict Validity Dates And Tokens To Just Membership Type Certificates

- CRM/Certificate/Form/CertificateConfigure.php
- templates/CRM/Certificate/Form/CertificateConfigure.hlp
Add help text to certificate download type field
> MMB-302: Add help text to certificate download type field

- CRM/Certificate/Entity/AbstractEntity.php
- CRM/Certificate/Entity/Membership.php
- CRM/Certificate/Hook/PageRun/EventPageTab.php
- CRM/Certificate/Hook/PageRun/MemberPageTab.php
- CRM/Certificate/Page/CertificateDownload.php
- CRM/Certificate/Service/Certificate.php
- js/compucertificate.js
- tests/phpunit/CRM/Certificate/Service/CertificateMembershipTest.php
Previously when a user attempted to create a certificate for an entity with the same configuration value, a Certificate Exist Exception was thrown, in this PR we now allow users to create a certificate for membership entity with similar configurations.
Error Message is thrown to the User for duplicate membership certificate
`A certificate configuration exist for the entity that satisfies either the selected status or type`
Error Message is now thrown to the User for duplicate membership certificate
Users can download multiple certificates by clicking on the `Print Certificate` button in the membership view.
> FOSFA-282: Support configuration of similar Membership certificate

- .github/workflows/unit-test.yml
- CRM/Certificate/Form/CertificateConfigure.php
- templates/CRM/Certificate/Form/CertificateConfigure.tpl
This PR will show the previously uploaded file name after creating a certificate with a "Download File" type when a user returns and edits the certificate.
> COMCL-803: Show previous uploaded file name

- CRM/Certificate/Service/CertificateMembership.php
- CRM/Certificate/Token/Case.php
- CRM/Certificate/Token/Certificate.php
- CRM/Certificate/Token/Event.php
- CRM/Certificate/Token/Membership.php
- CRM/Certificate/Token/Participant.php
- tests/phpunit/CRM/Certificate/Service/CertificateEventGeneratorTest.php
The current implementation for values of date tokens only support a fix format which is something like 31/Dec/2024. This pr adds the support for most of the different date formats that are supported by [this](https://www.php.net/manual/en/function.strftime.php) function.
Dates were being provided in just a single format for certificate date token values.
Now we can utilize [this](https://docs.civicrm.org/user/en/latest/common-workflows/tokens-and-mail-merge/#date) date formatting for certificate date tokens.
Currently we are providing string values for tokens, this pr changes the values to be a DateTime object so that civi formats the dates according to the given format. If no format is given then the default format that is defined in admin settings will be used
> MMB-437: Support Different Date Formats For Tokens

- CRM/Certificate/Service/CertificateMembership.php
Currently when querying for valid memberships to calculate token values we check that the membership start and end dates should be valid. This pr removes these date checks as we just need to consider the membership types and statuses configured in certificate configuration.
> MMB-284: Remove Date Checks From Valid Membership Query

- .github/workflows/unit-test.yml
- CRM/Certificate/Token/Membership.php
- info.xml
This pr creates three new tokens related to insurance premium amounts.
- Token 1: Insurance Premium (excl IPT): {certificate_membership.insurance_premium_ex_ipt}
- 
- Token 2: Insurance Premium (IPT): {certificate_membership.insurance_premium_ipt_only}
- 
- Token 3: Insurance Premium (incl IPT): {certificate_membership.insurance_premium_inc_ipt}
Tokens did not exist
> MMB-501: Add Insurance Premium Tokens

- certificate.php
This PR fixes the permission label warning
> [PHP User Deprecation] Permission 'configure certificates' should be declared with 'label' and 'description' keys. See https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_permission/ Caller: CRM_Core_Permission::assembleBasicPermissions at /var/www/default/htdocs/httpdocs/profiles/compuclient/modules/contrib/civicrm/CRM/Core/Error.php:1132
> CIVIMM-293: Fix permission label
